language: java
install: true

env:
  global:
  - CXX=g++-4.8
  - CF_APP=verycoolapp
  - secure: rcM3CvRRFb/Ke0sfsOVJClC1LJnaxWFZ7VAWwptnw3jjlgZ8Lrq9zDOsAh+NE1RVt6YMO7xiz1V/utXWpow/7OVilOCdFF+lfPrvBlc72mPWvw4DeCKhkRfcBSoCeP39Fm0OvRRdgfnx0xRUAkPoj11ArsQUA0u7ibzO0Zifi3yR9yJp0sHg27nU52kuWpKPv+Ehk66ZWvzpOiGl6wSZ4UunzNoEhMtQgE8vw7X5Om2Rxo3uC9vk19xBGu2zp/jR+XTJ8+ZoBoxI5Y8mQ5v96xmrAijUJtpx18H/gbqhhdQBmZ1dO14axgBX9Kgnesu2jKvohn4cbcYabPUoKaPq9UCevzu/OYoxtTIwi1jafG7fZjTnSukeQOotnUOFp3duZeyWZzdDNe2Ax0g6Cht8twQGj3ii7WIzl0wTSEEd35Z1dU/IG3lwfHkwCSxy5j9e4Ao4CZR2zkHbFu+Wp+oxY0kg1jRP8+F4JZN6PMsQjsGkikuecYkwuyHciym8Q/MXdORPNYIoQJ9mgt2BrAyaWb+ZAI1O8caaNzrPASNw7Zb/xkEAFMAYRg+zWONaEtZSfPZYw3DdUcO9hkFsVP5mBxoG6xRBYE2SFEOhit7yhAPOXak6xpDEBGZ9nXxrV/CU6Q9ldf0wj2PbZCL8UVqlNDsYRLotO0sTbPgzADwgH1Q=
  - secure: JsfJFjMsOaA9e0bPwmr0sg2Q8oFMoc/IjcGFBNh2XM2hs081KtlRvlaVO0Bdk7Qj4ykSAOXMMiuPRP/RXJDbb8n7zHeMv68w1lebStXr3P7sC53oa7tf7Pu+zlwIIVRA6SoAKDLy6sznSGHUBtmr+fYze21gXk92ZonOUuysb6CFpuZQfWgvTHNyzaQM7FqhsuOVSCY5w61p2G+8X1G2FeKNtu277q7Z1oxz2xmLrXenntzIpTK0wSvMCThmNJ47LVlzbMR3xeTqw4E/uj6jxQL9QpwHHnrAxWIm5JFyEgb1FbC/4uz9oMyY/4zvFLeIYFvSCMhvbqyLevfalLXI4qa19M1NtKM3kKEvLZpffmgREmewrq4FbQ8Slzv5h5mCKhH2KKn/651j98Em2vKaCkTA51KaWXlPJ2SJLMmLAJwx0x19dLaqwc7XzG8uIkvrriDhsPZ2v/5vapmtT0kMCOvOp2JVzI/YfYdxLC+vKjNhEuLAfFpgQAlrlTk9YJierWKdipa5DNV6vmTAPFLAkp+3/agT4RLqrWLvq5xjgTLvFfqYUJFG++Enf3ImXyaGc84uMN5P3MuY098cCAuThPv0iiDhpc3o//ZV0fN6JrkfsrWzUVhFiuIEdY76hDhpPafDVWj/+GVhl8EtpyOYcBJkuN+1J85yFt8OHQoUTqk=
script:
- sudo mkdir /mvnbuild
- mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Denv.CF_API=$CF_API -Denv.CF_ORGANIZATION=$CF_ORGANIZATION -Denv.CF_SPACE=$CF_SPACE -Denv.CF_USERNAME=$CF_USERNAME -Denv.CF_PASSWORD=$CF_PASSWORD
- mvn clean install -P cloud-integration-tests

- 'if [ $TRAVIS_TEST_RESULT -eq 0 ]; then
 chmod +x ./cf_blue_green_travis.sh;
 sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
 sudo apt-get -qq update;
 sudo apt-get -qq install g++-4.8;
 sudo ./cf_blue_green_travis.sh;
fi'

sudo: required
